phrase:
  access_token: 6793ef4095e83447bdf7942e0d4eba5738cb28b610b8676543df7ee21156c929
  project_id: 048644de1ce0b0173e0636ecfdd60628
  file format: xml
  
  
  push:
    sources:
    - file: ./locale/design_keys.xml
      params:
        file_format: xml
        locale_id: ee431f8848c5c33b4214e83116e6d54a
        update_translations: false
        
        
  pull:
    targets:
    - file: ./locale/design_keys_<locale_code>.xml
      params: 
        locale_id: 75698769af86b5c2d63b2b53eef7a6d1
        file_format: xml
    - file: ./locale/design_keys_<locale_code>.xml
      params: 
        locale_id: b1cf1f0011149b0f627a08aa618ffb91
        file_format: xml
    - file: ./locale/design_keys_<locale_code>.xml
      params: 
        locale_id: 503bd0fd4f6e83055b3a328451a4ef31
        file_format: xml
