phrase:
  access_token: 6793ef4095e83447bdf7942e0d4eba5738cb28b610b8676543df7ee21156c929
  project_id: ae0435c905ce64faf6ead4b6857f67d8
  file format: json
  
  
  push:
    sources:
    - file: ./locale/design_keys.xml
      params:
        file_format: xml
        locale_id: 49d852e766934ba68841f34e24de760c
        update_translations: true
        
        
  pull:
    targets:
    - file: ./locale/design_keys_<locale_code>.xml
      params:
        file_format: xml

