phrase:
  access_token: 6793ef4095e83447bdf7942e0d4eba5738cb28b610b8676543df7ee21156c929
  project_id: a9098423eddd49aace6e8aab562f5df5
  file_format: json
  
  
  push:
    sources:
    - file: ./locale/*.json
      params:
        file_format: json
        locale_id: d24ca12b80122492c4b3a6d672b8bb9c
        tags: tag2
        update_translations: true
  pull:
    targets:
    - file: ./locale/*.json
      params: 
        locale_id: d24ca12b80122492c4b3a6d672b8bb9c
        locale_ids: # Additional languages to include
          - 39c45c249f5a3cacc5b2a8878573b4f8
          - df95d47d78c5c516edb82706dd255b76
          - e712b4a56f887e24e27afd23554f6d6f
