phrase:
  access_token: 6793ef4095e83447bdf7942e0d4eba5738cb28b610b8676543df7ee21156c929
  project_id: a9098423eddd49aace6e8aab562f5df5
  file format: i18next
  
  
  push:
    sources:
    - file: ./locale/<tag>.json
      params:
        file_format: i18next
        locale_id: d24ca12b80122492c4b3a6d672b8bb9c
        update_translations: true
        
  pull:
    targets:
    - file: ./locale/design_keys_<locale_name>.json
      params: 
        locale_id: 39c45c249f5a3cacc5b2a8878573b4f8
        file_format: i18next
    - file: ./locale/design_keys_<locale_name>.json
      params: 
        locale_id: df95d47d78c5c516edb82706dd255b76
        file_format: i18next
    - file: ./locale/design_keys_<locale_name>.json
      params: 
        locale_id: e712b4a56f887e24e27afd23554f6d6f
        file_format: i18next
