phrase:
  access_token: 6793ef4095e83447bdf7942e0d4eba5738cb28b610b8676543df7ee21156c929
  project_id: d25965c352eddadc7c539cfe0b80645d
  file format: xml
  
  
  push:
    sources:
    - file: ./locale/*.xcstrings
      params:
        file_format: strings_catalog
        locale_id: 37463953af7c25bb965f21ab9916571f
        update_translations: true
        
  pull:
    targets:
    - file: ./locale/design_keys_<locale_name>.xcstrings
      params: 
        locale_id: cc815835644e1b88a85e818f92147712
        file_format: strings_catalog
